env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.base.json
plugins:
  - '@typescript-eslint'
rules:
  no-shadow: off
  no-console: off
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  import/extensions: off
  no-use-before-define: off
  no-useless-constructor: off
  quotes:
    - error
    - single
  '@typescript-eslint/quotes':
    - error
    - single



