name: CD Api

on:
  push:
    paths:
      - 'src/functions/**'
      - 'src/middlewares/**'
      - 'src/repository/**'
      - 'src/infra/**'
    branches:
      - main
  workflow_dispatch:

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Set env to prod
      if: endsWith(github.ref, '/main')
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        echo "::set-env name=NODE_ENV::dev"
        echo "::set-env name=TWITCH_EVENT_SUB_LISTENER_SECRET::${{ secrets.TWITCH_EVENT_SUB_LISTENER_SECRET }}"

    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Node version
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install aws cdk
      run: npm install -g aws-cdk

    - name: Build App
      id: build
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Bootstrap CDK
      id: bootstrap
      run: |
        cdk bootstrap

    - name: Deploy to aws
      id: deploy
      run: |
        NODE_ENV=$NODE_ENV TWITCH_EVENT_SUB_LISTENER_SECRET=$TWITCH_EVENT_SUB_LISTENER_SECRET cdk deploy --require-approval never